{% set name = "Deprecated" %}
{% set version = "1.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43ac5335da90c31c24ba028af536a91d41d53f9e6901ddb021bcc572ce44e38d

build:
  number: 0
  noarch: python
  script: python -m pip install --ignore-installed --no-deps .

requirements:
  host:
    - python
    - pip
    - wrapt <2,>=1.10
  run:
    - python >=2.7
    - wrapt <2,>=1.10

test:
  imports:
    - deprecated

about:
  home: https://github.com/tantale/deprecated
  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  summary: Python @deprecated decorator to deprecate old python classes, functions or methods.
  dev_url: https://github.com/tantale/deprecated

extra:
  recipe-maintainers:
    - mariusvniekerk
    - dbast
